## Numpy Module

In [2]:
import numpy as np       # Unpack the module numpy

### Creating & Accessing elements in 1D Array

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)      # Output: [1 2 3 4 5]

print("First Element : ", arr[0])      # Output: First Element :  1
print("Second Element : ", arr[1])     # Output: First Element :  2

[1 2 3 4 5]
First Element :  1
Second Element :  2


### Creating & Accessing elements in 2D Array

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)           # Output: [[1 2 3] 
                     #          [4 5 6]]

print(arr[0][0])        # Output: 1
print(arr[0][1])        # Output: 2
print(arr[0][2])        # Output: 3

print(arr[1][0])        # Output: 4
print(arr[1][1])        # Output: 5
print(arr[1][2])        # Output: 6

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


### Finding Dimension of the Array

In [14]:
b = np.array([1, 2, 3])   # 1D Array
print(b)         # Output:  [1 2 3]
print(b.ndim)    # Show the Dimension of the Array   / Output: 1 


c = np.array([[1, 2, 3], [4, 5, 6]])     # 2D Array
print(c)         # Output: [[1 2 3]
                   #        [4 5 6]]
print(c.ndim)    # Show the Dimension of the Array  / Output: 2 

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2


### Using Negative Indexing to access elements in 1D Array

In [19]:
a = np.array([1, 2, 3, 4, 5])
print(a[4])      
print(a[-1])   # a[4] = a[-1] = 5, Both Output: 5

5
5


### Using Negative Indexing to access in 2D Array

In [22]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a[1, -1])
print(a[1][-1])    # a[1, -1] = a[1][-1] = 10, Both Output: 10

10
10


### Slicing an Array

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])      # Output: [2 3 4 5]
print(arr[1:5:2])    # Output: [2 4]

[2 3 4 5]
[2 4]


### Checking Datatype of an Array

In [5]:
a = np.array([1, 2, 3, 4, 5])
print(a.dtype)        # Output: int64

int64


### Copy Operation on an Array

In [28]:
a = np.array([1, 2, 3, 4, 5])
x = a.copy()       # Copy Array of the Content a
a[0] = 100
x[0] = 200
print(a)       # Output : [100   2   3   4   5]
print(x)       # Output : [200   2   3   4   5]

[100   2   3   4   5]
[200   2   3   4   5]


### Iterating 1D Array

In [29]:
arr = np.array([1, 2, 3, 4, 5])
for i in arr:
    print(i)       
    
# Output: 
# 1
# 2
# 3
# 4
# 5

1
2
3
4
5


### Iterating 2D Array

In [61]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for x in arr:
    print(x)
    
# Output:
# [1 2 3 4 5]
# [ 6  7  8  9 10]

[1 2 3 4 5]
[ 6  7  8  9 10]


### Finding Shape of the Array

In [32]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.shape)      # Output : (2, 5) -> 2 rows and 5 columns

(2, 5)


### Reshaping 1D Array to 2D Array

In [34]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)      #  Output : [[ 1  2  3]
                        #  [ 4  5  6]
                        #  [ 7  8  9]
                        #  [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Joining Two Arrays

In [37]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr = np.concatenate((arr1, arr2))

print(arr)       # Output: [ 1  2  3  4  5  6  7  8  9 10]

[ 1  2  3  4  5  6  7  8  9 10]


### Splitting an Array

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr1 = np.array_split(arr, 3)
print(arr1)     # Output: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

arr2 = np.array_split(arr, 4)
print(arr2)    # Output: [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


### Sorting an Array

In [44]:
a = np.array([10, 4, 7, 9, 2, 0])
print(np.sort(a))       # Output: [ 0  2  4  7  9 10]

b = np.array(['cat', 'ant', 'dog'])
print(np.sort(b))       # Output: ['ant' 'cat' 'dog']

c = np.array([[10, 5, 9], [13, 0, 3]])
print(np.sort(c))       # Output: [[ 5  9 10]
                           #       [ 0  3 13]]

[ 0  2  4  7  9 10]
['ant' 'cat' 'dog']
[[ 5  9 10]
 [ 0  3 13]]


### Searching for an Element in Array

In [46]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)      # Output: (array([3, 5, 6]),)


# Find the indexes where the values are even:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(arr1 % 2 == 0)
print(y)      # Output: (array([1, 3, 5, 7]),)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)


### Filtering an Array

In [50]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
new_array = arr[x]

print(new_array)   # Output: [41 43]

[41 43]


### Generate a Random Integer

In [57]:
from numpy import random

x = random.randint(100)
print(x)       # Output: 17

28


### Generating a Random Array

In [59]:
from numpy import random

x = random.randint(100, size = (5))
print(x)        # Output: [71 13  4 10 25]

[42 34 78 34 12]
